services:
    database:
        container_name: cuisto-database
        image: postgres:16.4-alpine
        environment:
            POSTGRES_DB: cuisto
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        restart: unless-stopped
        healthcheck:
            test:
                - CMD-SHELL
                - 'pg_isready -U user -d cuisto'
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - cuisto_db_data:/var/lib/postgresql/data:rw

    app:
        container_name: cuisto-app
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        volumes:
            - .:/app
        command: sleep infinity
        depends_on:
            - database

    mailer:
        image: maildev/maildev
        container_name: cuisto-mailer
        command: bin/maildev --web 1080 --smtp 1025 --hide-extensions STARTTLS

volumes:
    cuisto_db_data: